export interface SystemGuideEntry {
  id: string;
  title: string;
  keywords: readonly string[];
  content: string;
  suggested_path: string | null;
}

export const SYSTEM_GUIDE: readonly SystemGuideEntry[] = [
  {
    id: "invoice-lifecycle",
    title: "Invoice lifecycle",
    keywords: ["invoice", "draft", "post", "posting", "cancel", "overdue"],
    content:
      "Invoices are created as governed financial documents. A Draft can be reviewed; posting makes the authoritative receivable and its journal entry. Posted financial fields are protected. Cancellation follows the governed cancellation path and records authoritative audit fields.",
    suggested_path: "/invoices",
  },
  {
    id: "receipt-lifecycle",
    title: "Receipt lifecycle and unapplied cash",
    keywords: ["receipt", "cash", "unapplied", "unallocated", "post", "cheque"],
    content:
      "Posting a receipt records cash. Any posted amount not allocated to an eligible invoice remains unapplied cash. The receipt keeps authoritative allocated and unallocated amounts; Allocation Wizard is the review surface.",
    suggested_path: "/receipts",
  },
  {
    id: "allocation",
    title: "Allocation",
    keywords: ["allocation", "allocate", "matching", "fifo", "payment"],
    content:
      "Allocation applies a posted receipt or eligible credit note to an open customer document. Deterministic validation checks customer, currency, outstanding amount, status, and concurrency. Reversals are governed and audited; the assistant cannot allocate or reverse money.",
    suggested_path: "/allocations",
  },
  {
    id: "credit-debit-notes",
    title: "Credit Notes and Debit Notes",
    keywords: ["credit note", "debit note", "cn", "dn"],
    content:
      "Credit Notes and Debit Notes share the Invoice-family authority. Credit Notes reduce eligible receivables through governed linkage/allocation; Debit Notes increase the receivable. Posting creates authoritative journal evidence.",
    suggested_path: "/credit-notes",
  },
  {
    id: "straight-through",
    title: "Straight-Through Automation",
    keywords: [
      "straight-through",
      "automation",
      "mode",
      "document intelligence",
    ],
    content:
      "Straight-Through mode permits eligible Gmail documents to move through document understanding, deterministic validation, governed Invoice/Receipt creation and posting, and deterministic allocation. AI candidates are never financial authority; failed gates create bounded exceptions instead of guessing.",
    suggested_path: "/automation",
  },
  {
    id: "exceptions",
    title: "Automation Exceptions",
    keywords: ["exception", "failed", "retry", "review", "attention"],
    content:
      "An Automation Exception is a fail-closed, reviewable record created when document processing, validation, matching, provider readiness, or delivery cannot proceed safely. Recovery and retry paths remain governed and auditable.",
    suggested_path: "/automation/exceptions",
  },
  {
    id: "reminders",
    title: "Reminder Evaluation and Delivery",
    keywords: ["reminder", "evaluation", "delivery", "gmail", "overdue"],
    content:
      "Reminder Evaluation determines whether an overdue invoice meets a configured reminder stage. Reminder Delivery is the separate governed provider step that sends an eligible reminder when delivery readiness is valid. Attempts and outcomes are recorded; evaluation does not itself prove delivery.",
    suggested_path: "/automation",
  },
  {
    id: "fx",
    title: "FX, booked rates, and base availability",
    keywords: [
      "fx",
      "exchange",
      "rate",
      "base amount",
      "base unavailable",
      "sgd",
      "myr",
    ],
    content:
      "New AR documents support MYR and SGD. MYR uses exact parity 1. SGD uses an authoritative transaction-date reference or governed override, then stores a booked FX snapshot. Company-base reporting uses booked FX, not today's market rate. A historical document without verified booked FX remains excluded rather than re-valued.",
    suggested_path: "/reports",
  },
  {
    id: "journals",
    title: "Journal Entries",
    keywords: ["journal", "je", "debit", "credit", "posting"],
    content:
      "Journal Entries are generated by governed financial posting and reversal flows. The read-only Journal viewer exposes balanced headers, debit/credit lines, GL accounts, source evidence, and reversal linkage. There is no manual journal editor.",
    suggested_path: "/journal-entries",
  },
  {
    id: "audit",
    title: "Audit Trail",
    keywords: ["audit", "history", "actor", "event", "change"],
    content:
      "Audit Trail is a read-only normalized view over stored authoritative lifecycle fields and event sources. It does not fabricate before/after values. Sensitive customer-change values are redacted and unknown actors remain unknown.",
    suggested_path: "/settings/audit-log",
  },
  {
    id: "reports",
    title: "Reports and exports",
    keywords: ["report", "aging", "export", "pdf", "excel", "xlsx"],
    content:
      "Report Center provides Aging, Invoice Summary, Receipt Summary, and Customer Outstanding reports. PDF and Excel exports are available within each report. Company-base totals include only authoritative booked-FX contributions.",
    suggested_path: "/reports",
  },
  {
    id: "roles",
    title: "Roles and permissions",
    keywords: [
      "role",
      "permission",
      "clerk",
      "supervisor",
      "finance manager",
      "auditor",
      "system admin",
    ],
    content:
      "AR Clerk is operational and assigned-customer scoped. AR Supervisor and Finance Manager have broader operational authority according to each feature. Auditor has governed read-only access. System Admin is configuration-oriented and does not gain financial operational access merely through administration screens or Copilot.",
    suggested_path: "/settings/roles",
  },
  {
    id: "mailbox",
    title: "Mailbox ingestion, delivery, and Sync Now",
    keywords: [
      "mailbox",
      "gmail",
      "ingestion",
      "delivery",
      "sync now",
      "oauth",
    ],
    content:
      "Mailbox ingestion receives source messages; Delivery is an independent credential/capability used for reminder sending. Sync Now invokes governed ingestion synchronization and does not grant delivery authority. OAuth credentials remain server-side and are never exposed by Copilot.",
    suggested_path: "/automation/mailboxes",
  },
  {
    id: "imports",
    title: "Invoice and Receipt imports",
    keywords: ["import", "csv", "excel", "xlsx", "rows"],
    content:
      "Invoice and Receipt imports accept governed CSV/Excel intake, validate rows, resolve customers, and expose review errors. Unsupported currencies and unsafe rows fail closed; they are not silently converted or skipped without explanation.",
    suggested_path: "/invoices/import",
  },
] as const;

function searchTerms(query: string): string[] {
  return query.toLowerCase().match(/[a-z0-9]+/g)?.filter((term) =>
    term.length > 1
  ) ?? [];
}

export function searchSystemGuide(query: string): SystemGuideEntry[] {
  const terms = searchTerms(query);
  if (terms.length === 0) return [];
  return SYSTEM_GUIDE.map((entry) => {
    const haystack = `${entry.title} ${
      entry.keywords.join(" ")
    } ${entry.content}`.toLowerCase();
    const score = terms.reduce(
      (total, term) => total + (haystack.includes(term) ? 1 : 0),
      0,
    );
    return { entry, score };
  }).filter((candidate) => candidate.score > 0)
    .sort((left, right) =>
      right.score - left.score || left.entry.id.localeCompare(right.entry.id)
    )
    .slice(0, 3)
    .map(({ entry }) => entry);
}
