import type { Config } from "tailwindcss";

/**
 * Colour is expressed entirely through CSS custom properties defined in
 * `globals.css`. Tailwind here only names them, so a utility such as
 * `text-slate-600` resolves to whichever theme is active instead of to a fixed
 * hex value. That is the mechanism by which the existing pages theme without
 * needing `dark:` variants.
 *
 * `<alpha-value>` is preserved on every entry so opacity modifiers
 * (`bg-surface/80`) keep working.
 */
const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        slate: {
          50: "rgb(var(--c-slate-50) / <alpha-value>)",
          100: "rgb(var(--c-slate-100) / <alpha-value>)",
          200: "rgb(var(--c-slate-200) / <alpha-value>)",
          300: "rgb(var(--c-slate-300) / <alpha-value>)",
          400: "rgb(var(--c-slate-400) / <alpha-value>)",
          500: "rgb(var(--c-slate-500) / <alpha-value>)",
          600: "rgb(var(--c-slate-600) / <alpha-value>)",
          700: "rgb(var(--c-slate-700) / <alpha-value>)",
          800: "rgb(var(--c-slate-800) / <alpha-value>)",
          900: "rgb(var(--c-slate-900) / <alpha-value>)",
          950: "rgb(var(--c-slate-950) / <alpha-value>)",
        },
        brand: {
          50: "rgb(var(--c-brand-50) / <alpha-value>)",
          100: "rgb(var(--c-brand-100) / <alpha-value>)",
          200: "rgb(var(--c-brand-200) / <alpha-value>)",
          300: "rgb(var(--c-brand-300) / <alpha-value>)",
          400: "rgb(var(--c-brand-400) / <alpha-value>)",
          500: "rgb(var(--c-brand-500) / <alpha-value>)",
          600: "rgb(var(--c-brand-600) / <alpha-value>)",
          700: "rgb(var(--c-brand-700) / <alpha-value>)",
          800: "rgb(var(--c-brand-800) / <alpha-value>)",
          900: "rgb(var(--c-brand-900) / <alpha-value>)",
          950: "rgb(var(--c-brand-950) / <alpha-value>)",
        },
        blue: {
          50: "rgb(var(--c-blue-50) / <alpha-value>)",
          100: "rgb(var(--c-blue-100) / <alpha-value>)",
          200: "rgb(var(--c-blue-200) / <alpha-value>)",
          300: "rgb(var(--c-blue-300) / <alpha-value>)",
          400: "rgb(var(--c-blue-400) / <alpha-value>)",
          500: "rgb(var(--c-blue-500) / <alpha-value>)",
          600: "rgb(var(--c-blue-600) / <alpha-value>)",
          700: "rgb(var(--c-blue-700) / <alpha-value>)",
          800: "rgb(var(--c-blue-800) / <alpha-value>)",
          900: "rgb(var(--c-blue-900) / <alpha-value>)",
        },
        emerald: {
          50: "rgb(var(--c-emerald-50) / <alpha-value>)",
          100: "rgb(var(--c-emerald-100) / <alpha-value>)",
          200: "rgb(var(--c-emerald-200) / <alpha-value>)",
          300: "rgb(var(--c-emerald-300) / <alpha-value>)",
          400: "rgb(var(--c-emerald-400) / <alpha-value>)",
          500: "rgb(var(--c-emerald-500) / <alpha-value>)",
          600: "rgb(var(--c-emerald-600) / <alpha-value>)",
          700: "rgb(var(--c-emerald-700) / <alpha-value>)",
          800: "rgb(var(--c-emerald-800) / <alpha-value>)",
          900: "rgb(var(--c-emerald-900) / <alpha-value>)",
        },
        red: {
          50: "rgb(var(--c-red-50) / <alpha-value>)",
          100: "rgb(var(--c-red-100) / <alpha-value>)",
          200: "rgb(var(--c-red-200) / <alpha-value>)",
          300: "rgb(var(--c-red-300) / <alpha-value>)",
          400: "rgb(var(--c-red-400) / <alpha-value>)",
          500: "rgb(var(--c-red-500) / <alpha-value>)",
          600: "rgb(var(--c-red-600) / <alpha-value>)",
          700: "rgb(var(--c-red-700) / <alpha-value>)",
          800: "rgb(var(--c-red-800) / <alpha-value>)",
          900: "rgb(var(--c-red-900) / <alpha-value>)",
        },
        amber: {
          50: "rgb(var(--c-amber-50) / <alpha-value>)",
          100: "rgb(var(--c-amber-100) / <alpha-value>)",
          200: "rgb(var(--c-amber-200) / <alpha-value>)",
          300: "rgb(var(--c-amber-300) / <alpha-value>)",
          400: "rgb(var(--c-amber-400) / <alpha-value>)",
          500: "rgb(var(--c-amber-500) / <alpha-value>)",
          600: "rgb(var(--c-amber-600) / <alpha-value>)",
          700: "rgb(var(--c-amber-700) / <alpha-value>)",
          800: "rgb(var(--c-amber-800) / <alpha-value>)",
          900: "rgb(var(--c-amber-900) / <alpha-value>)",
        },
        green: {
          50: "rgb(var(--c-green-50) / <alpha-value>)",
          100: "rgb(var(--c-green-100) / <alpha-value>)",
          200: "rgb(var(--c-green-200) / <alpha-value>)",
          300: "rgb(var(--c-green-300) / <alpha-value>)",
          400: "rgb(var(--c-green-400) / <alpha-value>)",
          500: "rgb(var(--c-green-500) / <alpha-value>)",
          600: "rgb(var(--c-green-600) / <alpha-value>)",
          700: "rgb(var(--c-green-700) / <alpha-value>)",
          800: "rgb(var(--c-green-800) / <alpha-value>)",
          900: "rgb(var(--c-green-900) / <alpha-value>)",
        },
        purple: {
          50: "rgb(var(--c-purple-50) / <alpha-value>)",
          100: "rgb(var(--c-purple-100) / <alpha-value>)",
          200: "rgb(var(--c-purple-200) / <alpha-value>)",
          300: "rgb(var(--c-purple-300) / <alpha-value>)",
          400: "rgb(var(--c-purple-400) / <alpha-value>)",
          500: "rgb(var(--c-purple-500) / <alpha-value>)",
          600: "rgb(var(--c-purple-600) / <alpha-value>)",
          700: "rgb(var(--c-purple-700) / <alpha-value>)",
          800: "rgb(var(--c-purple-800) / <alpha-value>)",
          900: "rgb(var(--c-purple-900) / <alpha-value>)",
        },
        gray: {
          50: "rgb(var(--c-gray-50) / <alpha-value>)",
          100: "rgb(var(--c-gray-100) / <alpha-value>)",
          200: "rgb(var(--c-gray-200) / <alpha-value>)",
          300: "rgb(var(--c-gray-300) / <alpha-value>)",
          400: "rgb(var(--c-gray-400) / <alpha-value>)",
          500: "rgb(var(--c-gray-500) / <alpha-value>)",
          600: "rgb(var(--c-gray-600) / <alpha-value>)",
          700: "rgb(var(--c-gray-700) / <alpha-value>)",
          800: "rgb(var(--c-gray-800) / <alpha-value>)",
          900: "rgb(var(--c-gray-900) / <alpha-value>)",
        },
        indigo: {
          50: "rgb(var(--c-indigo-50) / <alpha-value>)",
          100: "rgb(var(--c-indigo-100) / <alpha-value>)",
          200: "rgb(var(--c-indigo-200) / <alpha-value>)",
          300: "rgb(var(--c-indigo-300) / <alpha-value>)",
          400: "rgb(var(--c-indigo-400) / <alpha-value>)",
          500: "rgb(var(--c-indigo-500) / <alpha-value>)",
          600: "rgb(var(--c-indigo-600) / <alpha-value>)",
          700: "rgb(var(--c-indigo-700) / <alpha-value>)",
          800: "rgb(var(--c-indigo-800) / <alpha-value>)",
          900: "rgb(var(--c-indigo-900) / <alpha-value>)",
        },
        sky: {
          50: "rgb(var(--c-sky-50) / <alpha-value>)",
          100: "rgb(var(--c-sky-100) / <alpha-value>)",
          200: "rgb(var(--c-sky-200) / <alpha-value>)",
          300: "rgb(var(--c-sky-300) / <alpha-value>)",
          400: "rgb(var(--c-sky-400) / <alpha-value>)",
          500: "rgb(var(--c-sky-500) / <alpha-value>)",
          600: "rgb(var(--c-sky-600) / <alpha-value>)",
          700: "rgb(var(--c-sky-700) / <alpha-value>)",
          800: "rgb(var(--c-sky-800) / <alpha-value>)",
          900: "rgb(var(--c-sky-900) / <alpha-value>)",
        },
        orange: {
          50: "rgb(var(--c-orange-50) / <alpha-value>)",
          100: "rgb(var(--c-orange-100) / <alpha-value>)",
          200: "rgb(var(--c-orange-200) / <alpha-value>)",
          300: "rgb(var(--c-orange-300) / <alpha-value>)",
          400: "rgb(var(--c-orange-400) / <alpha-value>)",
          500: "rgb(var(--c-orange-500) / <alpha-value>)",
          600: "rgb(var(--c-orange-600) / <alpha-value>)",
          700: "rgb(var(--c-orange-700) / <alpha-value>)",
          800: "rgb(var(--c-orange-800) / <alpha-value>)",
          900: "rgb(var(--c-orange-900) / <alpha-value>)",
        },
        teal: {
          50: "rgb(var(--c-teal-50) / <alpha-value>)",
          100: "rgb(var(--c-teal-100) / <alpha-value>)",
          200: "rgb(var(--c-teal-200) / <alpha-value>)",
          300: "rgb(var(--c-teal-300) / <alpha-value>)",
          400: "rgb(var(--c-teal-400) / <alpha-value>)",
          500: "rgb(var(--c-teal-500) / <alpha-value>)",
          600: "rgb(var(--c-teal-600) / <alpha-value>)",
          700: "rgb(var(--c-teal-700) / <alpha-value>)",
          800: "rgb(var(--c-teal-800) / <alpha-value>)",
          900: "rgb(var(--c-teal-900) / <alpha-value>)",
        },
        violet: {
          50: "rgb(var(--c-violet-50) / <alpha-value>)",
          100: "rgb(var(--c-violet-100) / <alpha-value>)",
          200: "rgb(var(--c-violet-200) / <alpha-value>)",
          300: "rgb(var(--c-violet-300) / <alpha-value>)",
          400: "rgb(var(--c-violet-400) / <alpha-value>)",
          500: "rgb(var(--c-violet-500) / <alpha-value>)",
          600: "rgb(var(--c-violet-600) / <alpha-value>)",
          700: "rgb(var(--c-violet-700) / <alpha-value>)",
          800: "rgb(var(--c-violet-800) / <alpha-value>)",
          900: "rgb(var(--c-violet-900) / <alpha-value>)",
        },

        // ── Semantic surfaces ──────────────────────────────────────────────
        "app-bg": "rgb(var(--app-bg) / <alpha-value>)",
        surface: {
          DEFAULT: "rgb(var(--surface) / <alpha-value>)",
          elevated: "rgb(var(--surface-elevated) / <alpha-value>)",
          muted: "rgb(var(--surface-muted) / <alpha-value>)",
        },
        line: {
          DEFAULT: "rgb(var(--border) / <alpha-value>)",
          muted: "rgb(var(--border-muted) / <alpha-value>)",
          strong: "rgb(var(--border-strong) / <alpha-value>)",
        },
        content: {
          DEFAULT: "rgb(var(--text-primary) / <alpha-value>)",
          secondary: "rgb(var(--text-secondary) / <alpha-value>)",
          muted: "rgb(var(--text-muted) / <alpha-value>)",
          inverse: "rgb(var(--text-inverse) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "rgb(var(--brand) / <alpha-value>)",
          hover: "rgb(var(--brand-hover) / <alpha-value>)",
          muted: "rgb(var(--brand-muted) / <alpha-value>)",
          contrast: "rgb(var(--brand-contrast) / <alpha-value>)",
          fill: "rgb(var(--brand-fill) / <alpha-value>)",
          "fill-hover": "rgb(var(--brand-fill-hover) / <alpha-value>)",
          "fill-active": "rgb(var(--brand-fill-active) / <alpha-value>)",
        },
        feedback: {
          success: "rgb(var(--success) / <alpha-value>)",
          warning: "rgb(var(--warning) / <alpha-value>)",
          danger: "rgb(var(--danger) / <alpha-value>)",
          info: "rgb(var(--info) / <alpha-value>)",
        },
        nav: {
          bg: "rgb(var(--nav-bg) / <alpha-value>)",
          border: "rgb(var(--nav-border) / <alpha-value>)",
          hover: "rgb(var(--nav-item-hover) / <alpha-value>)",
          active: "rgb(var(--nav-item-active) / <alpha-value>)",
          text: "rgb(var(--nav-text) / <alpha-value>)",
          "text-active": "rgb(var(--nav-text-active) / <alpha-value>)",
        },
        table: {
          bg: "rgb(var(--table-bg) / <alpha-value>)",
          header: "rgb(var(--table-header) / <alpha-value>)",
          hover: "rgb(var(--table-row-hover) / <alpha-value>)",
          border: "rgb(var(--table-border) / <alpha-value>)",
        },
        input: {
          bg: "rgb(var(--input-bg) / <alpha-value>)",
          border: "rgb(var(--input-border) / <alpha-value>)",
        },

        // Retained for existing sidebar markup; now theme-aware.
        sidebar: {
          bg: "rgb(var(--nav-bg) / <alpha-value>)",
          hover: "rgb(var(--nav-item-hover) / <alpha-value>)",
          active: "rgb(var(--nav-item-active) / <alpha-value>)",
          border: "rgb(var(--nav-border) / <alpha-value>)",
          text: "rgb(var(--nav-text) / <alpha-value>)",
          "text-active": "rgb(var(--nav-text-active) / <alpha-value>)",
        },

        // Status hues stay chromatic in both themes; only their tints move.
        status: {
          draft: "#64748b",
          open: "#3b82f6",
          overdue: "#ef4444",
          paid: "#22c55e",
          partial: "#f59e0b",
          cancelled: "#6b7280",
          blocked: "#dc2626",
          active: "#10b981",
          inactive: "#9ca3af",
        },
      },
      boxShadow: {
        card: "var(--shadow-card)",
        elevated: "var(--shadow-elevated)",
        glow: "var(--glow-brand)",
        "glow-subtle": "var(--glow-subtle)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        emphasized: "var(--ease-emphasized)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        normal: "var(--motion-normal)",
        slow: "var(--motion-slow)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      borderRadius: {
        lg: "0.625rem",
        md: "0.5rem",
        sm: "0.375rem",
      },
      animation: {
        "slide-in-right": "slideInRight var(--motion-slow) var(--ease-emphasized)",
        "fade-in": "fadeIn var(--motion-normal) var(--ease-emphasized)",
      },
      keyframes: {
        slideInRight: {
          "0%": { transform: "translateX(100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
