-- ============================================================================
-- TSH Synergy ERP - AR Module - 007c_api_staging_fixtures.sql
-- P1 API-layer staging fixtures
-- Run AFTER database/007_financial_rpcs.sql on Supabase staging.
-- ============================================================================
-- Staging only. Do not run on production.
--
-- Purpose:
--   Creates persistent deterministic data for Postman/curl API smoke tests.
--   This file intentionally COMMITs. It does not ROLLBACK.
--
-- Re-runnable:
--   The script resets only the deterministic P1API fixture rows. It does not
--   delete auth users and does not insert user_roles because real Supabase Auth
--   user UUIDs must be copied from the staging dashboard first.
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: CONSTANT FIXTURE UUIDs
-- ============================================================================
-- Main company:
--   81000000-0000-0000-0000-000000000001
-- Cross-company negative-test company:
--   81000000-0000-0000-0000-000000000002
--
-- Assigned customer:
--   85000000-0000-0000-0000-000000000001
-- Unassigned customer:
--   85000000-0000-0000-0000-000000000002

-- ============================================================================
-- SECTION 2: RESET PRIOR API TEST MUTATIONS FOR THIS FIXTURE SET
-- ============================================================================

-- Break self-references before deleting JEs generated by previous API runs.
UPDATE journal_entries
SET original_je_id = NULL,
    reversal_je_id = NULL
WHERE company_id IN (
  '81000000-0000-0000-0000-000000000001',
  '81000000-0000-0000-0000-000000000002'
)
AND (
  source_doc_id IN (
    '86000000-0000-0000-0000-000000000001',
    '86000000-0000-0000-0000-000000000002',
    '86000000-0000-0000-0000-000000000003',
    '86000000-0000-0000-0000-000000000004',
    '86000000-0000-0000-0000-000000000005',
    '86000000-0000-0000-0000-000000000006',
    '88000000-0000-0000-0000-000000000001',
    '88000000-0000-0000-0000-000000000002',
    '88000000-0000-0000-0000-000000000003',
    '88000000-0000-0000-0000-000000000004',
    '88000000-0000-0000-0000-000000000005',
    '88000000-0000-0000-0000-000000000006',
    '89000000-0000-0000-0000-000000000001',
    '89000000-0000-0000-0000-000000000002'
  )
  OR source_doc_no LIKE 'P1API-%'
  OR je_no LIKE 'P1API-%'
);

DELETE FROM journal_entries
WHERE company_id IN (
  '81000000-0000-0000-0000-000000000001',
  '81000000-0000-0000-0000-000000000002'
)
AND (
  source_doc_id IN (
    '86000000-0000-0000-0000-000000000001',
    '86000000-0000-0000-0000-000000000002',
    '86000000-0000-0000-0000-000000000003',
    '86000000-0000-0000-0000-000000000004',
    '86000000-0000-0000-0000-000000000005',
    '86000000-0000-0000-0000-000000000006',
    '88000000-0000-0000-0000-000000000001',
    '88000000-0000-0000-0000-000000000002',
    '88000000-0000-0000-0000-000000000003',
    '88000000-0000-0000-0000-000000000004',
    '88000000-0000-0000-0000-000000000005',
    '88000000-0000-0000-0000-000000000006',
    '89000000-0000-0000-0000-000000000001',
    '89000000-0000-0000-0000-000000000002'
  )
  OR source_doc_no LIKE 'P1API-%'
  OR je_no LIKE 'P1API-%'
);

-- Do not reset credit_control_logs. Audit/log tables are append-only and are
-- protected by fn_prevent_audit_log_modification() for financial compliance.
-- Re-runs may leave old P1API bounced-cheque log rows; API verification should
-- inspect new rows by created_at/source details after each bounce test instead.

DELETE FROM allocation_details
WHERE id IN (
  '89000000-0000-0000-0000-000000000001',
  '89000000-0000-0000-0000-000000000002'
)
OR receipt_id IN (
  '88000000-0000-0000-0000-000000000002',
  '88000000-0000-0000-0000-000000000003',
  '88000000-0000-0000-0000-000000000004'
);

DELETE FROM invoice_lines
WHERE invoice_id IN (
  '86000000-0000-0000-0000-000000000001',
  '86000000-0000-0000-0000-000000000002',
  '86000000-0000-0000-0000-000000000003',
  '86000000-0000-0000-0000-000000000004',
  '86000000-0000-0000-0000-000000000005',
  '86000000-0000-0000-0000-000000000006'
);

DELETE FROM receipts
WHERE id IN (
  '88000000-0000-0000-0000-000000000001',
  '88000000-0000-0000-0000-000000000002',
  '88000000-0000-0000-0000-000000000003',
  '88000000-0000-0000-0000-000000000004',
  '88000000-0000-0000-0000-000000000005',
  '88000000-0000-0000-0000-000000000006'
);

DELETE FROM invoices
WHERE id IN (
  '86000000-0000-0000-0000-000000000001',
  '86000000-0000-0000-0000-000000000002',
  '86000000-0000-0000-0000-000000000003',
  '86000000-0000-0000-0000-000000000004',
  '86000000-0000-0000-0000-000000000005',
  '86000000-0000-0000-0000-000000000006'
);

-- ============================================================================
-- SECTION 3: BASE COMPANY, PERIOD, GL, CONFIG, BANK, CUSTOMERS
-- ============================================================================

INSERT INTO companies (
  id, company_code, company_name, registration_no, tax_id, base_currency,
  country, address_line1, city, postal_code, email, is_active
)
VALUES
  (
    '81000000-0000-0000-0000-000000000001',
    'P1API',
    'P1 API Staging Test Company',
    'P1API-UEN',
    'P1API-TAX',
    'SGD',
    'SG',
    '1 API Test Street',
    'Singapore',
    '100001',
    'p1api@example.test',
    TRUE
  ),
  (
    '81000000-0000-0000-0000-000000000002',
    'P1XCO',
    'P1 API Cross Company',
    'P1XCO-UEN',
    'P1XCO-TAX',
    'SGD',
    'SG',
    '2 API Test Street',
    'Singapore',
    '100002',
    'p1xco@example.test',
    TRUE
  )
ON CONFLICT (id) DO UPDATE SET
  company_name = EXCLUDED.company_name,
  base_currency = EXCLUDED.base_currency,
  country = EXCLUDED.country,
  is_active = TRUE;

INSERT INTO fiscal_periods (id, company_id, period_code, status, start_date, end_date)
VALUES
  (
    '81000000-0000-0000-0000-000000000101',
    '81000000-0000-0000-0000-000000000001',
    to_char(CURRENT_DATE, 'YYYY-MM'),
    'Open',
    date_trunc('month', CURRENT_DATE)::DATE,
    (date_trunc('month', CURRENT_DATE) + INTERVAL '1 month - 1 day')::DATE
  ),
  (
    '81000000-0000-0000-0000-000000000102',
    '81000000-0000-0000-0000-000000000002',
    to_char(CURRENT_DATE, 'YYYY-MM'),
    'Open',
    date_trunc('month', CURRENT_DATE)::DATE,
    (date_trunc('month', CURRENT_DATE) + INTERVAL '1 month - 1 day')::DATE
  )
ON CONFLICT (company_id, period_code) DO UPDATE SET
  status = 'Open',
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date;

INSERT INTO gl_accounts (id, company_id, account_code, account_name, account_type, is_active)
VALUES
  ('83000000-0000-0000-0000-000000000001','81000000-0000-0000-0000-000000000001','P1API-1000','P1API Bank','Asset',TRUE),
  ('83000000-0000-0000-0000-000000000002','81000000-0000-0000-0000-000000000001','P1API-1050','P1API Cheques on Hand','Asset',TRUE),
  ('83000000-0000-0000-0000-000000000003','81000000-0000-0000-0000-000000000001','P1API-1100','P1API Trade Receivable','Asset',TRUE),
  ('83000000-0000-0000-0000-000000000004','81000000-0000-0000-0000-000000000001','P1API-2200','P1API Output Tax','Liability',TRUE),
  ('83000000-0000-0000-0000-000000000005','81000000-0000-0000-0000-000000000001','P1API-4000','P1API Revenue','Revenue',TRUE),
  ('83000000-0000-0000-0000-000000000006','81000000-0000-0000-0000-000000000001','P1API-6100','P1API Sales Discount','Expense',TRUE),
  ('83000000-0000-0000-0000-000000000007','81000000-0000-0000-0000-000000000001','P1API-7000','P1API Forex Gain','Revenue',TRUE),
  ('83000000-0000-0000-0000-000000000008','81000000-0000-0000-0000-000000000001','P1API-7100','P1API Forex Loss','Expense',TRUE),
  ('83000000-0000-0000-0000-000000000101','81000000-0000-0000-0000-000000000002','P1XCO-1000','P1XCO Bank','Asset',TRUE),
  ('83000000-0000-0000-0000-000000000103','81000000-0000-0000-0000-000000000002','P1XCO-1100','P1XCO Trade Receivable','Asset',TRUE),
  ('83000000-0000-0000-0000-000000000105','81000000-0000-0000-0000-000000000002','P1XCO-4000','P1XCO Revenue','Revenue',TRUE)
ON CONFLICT (id) DO UPDATE SET
  account_name = EXCLUDED.account_name,
  account_type = EXCLUDED.account_type,
  is_active = TRUE;

INSERT INTO ar_system_config (company_id, config_key, config_value, description)
VALUES
  ('81000000-0000-0000-0000-000000000001','invoice_future_days_limit','7','P1 API fixture'),
  ('81000000-0000-0000-0000-000000000001','default_ar_control_acct','P1API-1100','P1 API fixture'),
  ('81000000-0000-0000-0000-000000000001','default_revenue_acct','P1API-4000','P1 API fixture'),
  ('81000000-0000-0000-0000-000000000001','default_cheque_acct','P1API-1050','P1 API fixture'),
  ('81000000-0000-0000-0000-000000000001','default_discount_acct','P1API-6100','P1 API fixture'),
  ('81000000-0000-0000-0000-000000000001','default_forex_gain_acct','P1API-7000','P1 API fixture'),
  ('81000000-0000-0000-0000-000000000001','default_forex_loss_acct','P1API-7100','P1 API fixture'),
  ('81000000-0000-0000-0000-000000000002','default_ar_control_acct','P1XCO-1100','P1 API fixture cross company'),
  ('81000000-0000-0000-0000-000000000002','default_revenue_acct','P1XCO-4000','P1 API fixture cross company')
ON CONFLICT (company_id, config_key) DO UPDATE SET
  config_value = EXCLUDED.config_value,
  description = EXCLUDED.description;

INSERT INTO document_sequences (company_id, doc_type, prefix, current_year, current_month, last_sequence)
VALUES
  ('81000000-0000-0000-0000-000000000001','JE','JE-',EXTRACT(YEAR FROM CURRENT_DATE)::INT,EXTRACT(MONTH FROM CURRENT_DATE)::INT,100),
  ('81000000-0000-0000-0000-000000000002','JE','JE-',EXTRACT(YEAR FROM CURRENT_DATE)::INT,EXTRACT(MONTH FROM CURRENT_DATE)::INT,100)
ON CONFLICT (company_id, doc_type, current_year, current_month) DO UPDATE SET
  prefix = EXCLUDED.prefix,
  last_sequence = GREATEST(document_sequences.last_sequence, EXCLUDED.last_sequence);

INSERT INTO payment_terms (id, company_id, term_code, term_name, term_type, days, is_active)
VALUES (
  '81000000-0000-0000-0000-000000000201',
  '81000000-0000-0000-0000-000000000001',
  'P1API-N30',
  'P1 API Net 30',
  'Fixed Days',
  30,
  TRUE
)
ON CONFLICT (id) DO UPDATE SET
  term_name = EXCLUDED.term_name,
  term_type = EXCLUDED.term_type,
  days = EXCLUDED.days,
  is_active = TRUE;

INSERT INTO bank_accounts (
  id, company_id, bank_name, account_name, account_no, swift_code, currency, gl_account_id, is_active
)
VALUES (
  '84000000-0000-0000-0000-000000000001',
  '81000000-0000-0000-0000-000000000001',
  'P1 API Bank',
  'P1 API Operating Account',
  'P1API-001',
  'P1APISG1',
  'SGD',
  '83000000-0000-0000-0000-000000000001',
  TRUE
)
ON CONFLICT (id) DO UPDATE SET
  bank_name = EXCLUDED.bank_name,
  account_name = EXCLUDED.account_name,
  currency = EXCLUDED.currency,
  gl_account_id = EXCLUDED.gl_account_id,
  is_active = TRUE;

INSERT INTO customers (
  id, company_id, customer_id, customer_name, short_name, customer_type, status,
  bill_addr_line1, bill_city, bill_state, bill_postal, bill_country,
  contact_name, contact_phone, contact_email,
  default_currency, ar_control_acct_id, revenue_acct_id, tax_output_acct_id,
  discount_acct_id, forex_gain_acct_id, forex_loss_acct_id, payment_term_id,
  credit_limit, credit_rating, is_deleted
)
VALUES
  (
    '85000000-0000-0000-0000-000000000001',
    '81000000-0000-0000-0000-000000000001',
    'P1API-CUST-001',
    'P1 API Assigned Customer',
    'P1 Assigned',
    'Corporate',
    'Active',
    '1 Assigned Street',
    'Singapore',
    'SG',
    '100001',
    'SG',
    'Assigned Contact',
    '60000001',
    'p1api.assigned@example.test',
    'SGD',
    '83000000-0000-0000-0000-000000000003',
    '83000000-0000-0000-0000-000000000005',
    '83000000-0000-0000-0000-000000000004',
    '83000000-0000-0000-0000-000000000006',
    '83000000-0000-0000-0000-000000000007',
    '83000000-0000-0000-0000-000000000008',
    '81000000-0000-0000-0000-000000000201',
    999999,
    'A',
    FALSE
  ),
  (
    '85000000-0000-0000-0000-000000000002',
    '81000000-0000-0000-0000-000000000001',
    'P1API-CUST-002',
    'P1 API Unassigned Customer',
    'P1 Unassigned',
    'Corporate',
    'Active',
    '2 Unassigned Street',
    'Singapore',
    'SG',
    '100002',
    'SG',
    'Unassigned Contact',
    '60000002',
    'p1api.unassigned@example.test',
    'SGD',
    '83000000-0000-0000-0000-000000000003',
    '83000000-0000-0000-0000-000000000005',
    '83000000-0000-0000-0000-000000000004',
    '83000000-0000-0000-0000-000000000006',
    '83000000-0000-0000-0000-000000000007',
    '83000000-0000-0000-0000-000000000008',
    '81000000-0000-0000-0000-000000000201',
    999999,
    'A',
    FALSE
  )
ON CONFLICT (id) DO UPDATE SET
  customer_name = EXCLUDED.customer_name,
  status = 'Active',
  credit_limit = EXCLUDED.credit_limit,
  is_deleted = FALSE;

-- ============================================================================
-- SECTION 4: TRANSACTION FIXTURES
-- ============================================================================

INSERT INTO invoices (
  id, company_id, invoice_no, doc_type, invoice_date, due_date,
  customer_id, customer_name, currency, exchange_rate, base_currency,
  subtotal, tax_total, total_amount, base_total, outstanding,
  status, posting_period, reference_no, ar_acct, posted_by, posted_at,
  cancelled_by, cancelled_at, cancel_reason, version
)
VALUES
  -- Draft invoice for POST /invoices/:id/post.
  ('86000000-0000-0000-0000-000000000001','81000000-0000-0000-0000-000000000001','P1API-INV-POST','Invoice',CURRENT_DATE,NULL,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','SGD',1,'SGD',100,0,100,100,0,'Draft',NULL,'P1API post invoice',NULL,NULL,NULL,NULL,NULL,NULL,1),
  -- Open invoice for manual allocation.
  ('86000000-0000-0000-0000-000000000002','81000000-0000-0000-0000-000000000001','P1API-INV-ALLOC','Invoice',CURRENT_DATE,CURRENT_DATE + 30,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','SGD',1,'SGD',120,0,120,120,120,'Open',to_char(CURRENT_DATE,'YYYY-MM'),'P1API manual allocation','P1API-1100',NULL,NOW(),NULL,NULL,NULL,1),
  -- Partially paid invoice with active allocation for reverse_allocation.
  ('86000000-0000-0000-0000-000000000003','81000000-0000-0000-0000-000000000001','P1API-INV-REV-ALLOC','Invoice',CURRENT_DATE,CURRENT_DATE + 30,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','SGD',1,'SGD',80,0,80,80,10,'Partially Paid',to_char(CURRENT_DATE,'YYYY-MM'),'P1API reverse allocation','P1API-1100',NULL,NOW(),NULL,NULL,NULL,1),
  -- Open unallocated posted invoice for cancel invoice / reverse JE path.
  ('86000000-0000-0000-0000-000000000004','81000000-0000-0000-0000-000000000001','P1API-INV-CANCEL','Invoice',CURRENT_DATE,CURRENT_DATE + 30,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','SGD',1,'SGD',100,0,100,100,100,'Open',to_char(CURRENT_DATE,'YYYY-MM'),'P1API cancel invoice','P1API-1100',NULL,NOW(),NULL,NULL,NULL,1),
  -- Paid invoice allocated to posted cheque receipt for bounced cheque.
  ('86000000-0000-0000-0000-000000000005','81000000-0000-0000-0000-000000000001','P1API-INV-BOUNCE','Invoice',CURRENT_DATE,CURRENT_DATE + 30,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','SGD',1,'SGD',70,0,70,70,0,'Paid',to_char(CURRENT_DATE,'YYYY-MM'),'P1API bounced cheque','P1API-1100',NULL,NOW(),NULL,NULL,NULL,1),
  -- Unassigned customer draft invoice for AR Clerk denial.
  ('86000000-0000-0000-0000-000000000006','81000000-0000-0000-0000-000000000001','P1API-INV-UNASSIGNED','Invoice',CURRENT_DATE,NULL,'85000000-0000-0000-0000-000000000002','P1 API Unassigned Customer','SGD',1,'SGD',60,0,60,60,0,'Draft',NULL,'P1API unassigned invoice',NULL,NULL,NULL,NULL,NULL,NULL,1);

INSERT INTO invoice_lines (
  id, invoice_id, line_no, description, quantity, uom, unit_price,
  discount_pct, discount_amt, line_amount, tax_rate, tax_amount, line_total,
  gl_account_id
)
VALUES
  ('87000000-0000-0000-0000-000000000001','86000000-0000-0000-0000-000000000001',10,'P1API post invoice line',1,'EA',100,0,0,100,0,0,100,'83000000-0000-0000-0000-000000000005'),
  ('87000000-0000-0000-0000-000000000002','86000000-0000-0000-0000-000000000002',10,'P1API manual allocation line',1,'EA',120,0,0,120,0,0,120,'83000000-0000-0000-0000-000000000005'),
  ('87000000-0000-0000-0000-000000000003','86000000-0000-0000-0000-000000000003',10,'P1API reverse allocation line',1,'EA',80,0,0,80,0,0,80,'83000000-0000-0000-0000-000000000005'),
  ('87000000-0000-0000-0000-000000000004','86000000-0000-0000-0000-000000000004',10,'P1API cancel invoice line',1,'EA',100,0,0,100,0,0,100,'83000000-0000-0000-0000-000000000005'),
  ('87000000-0000-0000-0000-000000000005','86000000-0000-0000-0000-000000000005',10,'P1API bounced cheque line',1,'EA',70,0,0,70,0,0,70,'83000000-0000-0000-0000-000000000005'),
  ('87000000-0000-0000-0000-000000000006','86000000-0000-0000-0000-000000000006',10,'P1API unassigned line',1,'EA',60,0,0,60,0,0,60,'83000000-0000-0000-0000-000000000005');

INSERT INTO receipts (
  id, company_id, receipt_no, receipt_date, value_date,
  customer_id, customer_name, payment_method, currency, exchange_rate,
  base_currency, receipt_amount, base_amount, allocated_amount,
  unallocated_amount, bank_account_id, bank_account_name, reference_no,
  cheque_date, status, posting_period, remarks, posted_by, posted_at
)
VALUES
  -- Draft receipt for POST /receipts/:id/post.
  ('88000000-0000-0000-0000-000000000001','81000000-0000-0000-0000-000000000001','P1API-RCT-POST',CURRENT_DATE,CURRENT_DATE,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','TT','SGD',1,'SGD',100,100,0,100,'84000000-0000-0000-0000-000000000001','P1 API Operating Account','P1API receipt post',NULL,'Draft',NULL,'P1API draft receipt',NULL,NULL),
  -- Posted receipt for manual allocation.
  ('88000000-0000-0000-0000-000000000002','81000000-0000-0000-0000-000000000001','P1API-RCT-ALLOC',CURRENT_DATE,CURRENT_DATE,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','TT','SGD',1,'SGD',120,120,0,120,'84000000-0000-0000-0000-000000000001','P1 API Operating Account','P1API manual allocation',NULL,'Posted',to_char(CURRENT_DATE,'YYYY-MM'),'P1API posted receipt',NULL,NOW()),
  -- Posted partially allocated receipt for reverse allocation.
  ('88000000-0000-0000-0000-000000000003','81000000-0000-0000-0000-000000000001','P1API-RCT-REV-ALLOC',CURRENT_DATE,CURRENT_DATE,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','TT','SGD',1,'SGD',80,80,70,10,'84000000-0000-0000-0000-000000000001','P1 API Operating Account','P1API reverse allocation',NULL,'Posted',to_char(CURRENT_DATE,'YYYY-MM'),'P1API active allocation receipt',NULL,NOW()),
  -- Posted fully allocated cheque receipt for bounced cheque.
  ('88000000-0000-0000-0000-000000000004','81000000-0000-0000-0000-000000000001','P1API-RCT-BOUNCE',CURRENT_DATE,CURRENT_DATE,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','CHQ','SGD',1,'SGD',70,70,70,0,'84000000-0000-0000-0000-000000000001','P1 API Operating Account','P1API-CHQ-001',CURRENT_DATE,'Fully Allocated',to_char(CURRENT_DATE,'YYYY-MM'),'P1API cheque receipt',NULL,NOW()),
  -- Posted non-CHQ receipt for bounce negative path.
  ('88000000-0000-0000-0000-000000000005','81000000-0000-0000-0000-000000000001','P1API-RCT-NONCHQ',CURRENT_DATE,CURRENT_DATE,'85000000-0000-0000-0000-000000000001','P1 API Assigned Customer','TT','SGD',1,'SGD',30,30,0,30,'84000000-0000-0000-0000-000000000001','P1 API Operating Account','P1API non cheque',NULL,'Posted',to_char(CURRENT_DATE,'YYYY-MM'),'P1API non cheque receipt',NULL,NOW()),
  -- Unassigned customer draft receipt for AR Clerk denial.
  ('88000000-0000-0000-0000-000000000006','81000000-0000-0000-0000-000000000001','P1API-RCT-UNASSIGNED',CURRENT_DATE,CURRENT_DATE,'85000000-0000-0000-0000-000000000002','P1 API Unassigned Customer','TT','SGD',1,'SGD',60,60,0,60,'84000000-0000-0000-0000-000000000001','P1 API Operating Account','P1API unassigned receipt',NULL,'Draft',NULL,'P1API unassigned receipt',NULL,NULL);

INSERT INTO allocation_details (
  id, receipt_id, invoice_id, doc_type, allocated_amount, base_allocated,
  invoice_rate, receipt_rate, forex_gain_loss, discount_amount,
  allocation_date, allocated_by, allocation_method, status,
  reversed_by, reversed_at, reverse_reason
)
VALUES
  ('89000000-0000-0000-0000-000000000001','88000000-0000-0000-0000-000000000003','86000000-0000-0000-0000-000000000003','Invoice',70,70,1,1,0,0,NOW(),NULL,'Manual','Active',NULL,NULL,NULL),
  ('89000000-0000-0000-0000-000000000002','88000000-0000-0000-0000-000000000004','86000000-0000-0000-0000-000000000005','Invoice',70,70,1,1,0,0,NOW(),NULL,'Manual','Active',NULL,NULL,NULL);

-- ============================================================================
-- SECTION 5: BALANCED POSTED JOURNAL ENTRIES FOR PRE-POSTED FIXTURES
-- ============================================================================

INSERT INTO journal_entries (
  id, company_id, je_no, je_date, posting_period, source_type, source_doc_no,
  source_doc_id, description, currency, exchange_rate, base_currency,
  total_debit, total_credit, is_reversal, is_reversed, created_by
)
VALUES
  ('8a000000-0000-0000-0000-000000000002','81000000-0000-0000-0000-000000000001','P1API-JE-INV-ALLOC',CURRENT_DATE,to_char(CURRENT_DATE,'YYYY-MM'),'INV','P1API-INV-ALLOC','86000000-0000-0000-0000-000000000002','P1API posted invoice for manual allocation','SGD',1,'SGD',120,120,FALSE,FALSE,NULL),
  ('8a000000-0000-0000-0000-000000000003','81000000-0000-0000-0000-000000000001','P1API-JE-INV-REV-ALLOC',CURRENT_DATE,to_char(CURRENT_DATE,'YYYY-MM'),'INV','P1API-INV-REV-ALLOC','86000000-0000-0000-0000-000000000003','P1API posted invoice for reverse allocation','SGD',1,'SGD',80,80,FALSE,FALSE,NULL),
  ('8a000000-0000-0000-0000-000000000004','81000000-0000-0000-0000-000000000001','P1API-JE-INV-CANCEL',CURRENT_DATE,to_char(CURRENT_DATE,'YYYY-MM'),'INV','P1API-INV-CANCEL','86000000-0000-0000-0000-000000000004','P1API posted invoice for cancel/reversal','SGD',1,'SGD',100,100,FALSE,FALSE,NULL),
  ('8a000000-0000-0000-0000-000000000005','81000000-0000-0000-0000-000000000001','P1API-JE-INV-BOUNCE',CURRENT_DATE,to_char(CURRENT_DATE,'YYYY-MM'),'INV','P1API-INV-BOUNCE','86000000-0000-0000-0000-000000000005','P1API posted invoice for bounced cheque','SGD',1,'SGD',70,70,FALSE,FALSE,NULL),
  ('8b000000-0000-0000-0000-000000000002','81000000-0000-0000-0000-000000000001','P1API-JE-RCT-ALLOC',CURRENT_DATE,to_char(CURRENT_DATE,'YYYY-MM'),'RCT','P1API-RCT-ALLOC','88000000-0000-0000-0000-000000000002','P1API posted receipt for manual allocation','SGD',1,'SGD',120,120,FALSE,FALSE,NULL),
  ('8b000000-0000-0000-0000-000000000003','81000000-0000-0000-0000-000000000001','P1API-JE-RCT-REV-ALLOC',CURRENT_DATE,to_char(CURRENT_DATE,'YYYY-MM'),'RCT','P1API-RCT-REV-ALLOC','88000000-0000-0000-0000-000000000003','P1API posted receipt for reverse allocation','SGD',1,'SGD',80,80,FALSE,FALSE,NULL),
  ('8b000000-0000-0000-0000-000000000004','81000000-0000-0000-0000-000000000001','P1API-JE-RCT-BOUNCE',CURRENT_DATE,to_char(CURRENT_DATE,'YYYY-MM'),'RCT','P1API-RCT-BOUNCE','88000000-0000-0000-0000-000000000004','P1API posted cheque receipt for bounce','SGD',1,'SGD',70,70,FALSE,FALSE,NULL),
  ('8b000000-0000-0000-0000-000000000005','81000000-0000-0000-0000-000000000001','P1API-JE-RCT-NONCHQ',CURRENT_DATE,to_char(CURRENT_DATE,'YYYY-MM'),'RCT','P1API-RCT-NONCHQ','88000000-0000-0000-0000-000000000005','P1API posted non-CHQ receipt','SGD',1,'SGD',30,30,FALSE,FALSE,NULL);

INSERT INTO journal_entry_lines (
  id, je_id, line_no, gl_account_id, description, debit_amount, credit_amount,
  base_debit, base_credit, currency, original_amount
)
VALUES
  -- Invoice JEs: Dr AR, Cr Revenue.
  ('8c000000-0000-0000-0000-000000000021','8a000000-0000-0000-0000-000000000002',10,'83000000-0000-0000-0000-000000000003','P1API AR invoice allocation',120,0,120,0,'SGD',120),
  ('8c000000-0000-0000-0000-000000000022','8a000000-0000-0000-0000-000000000002',20,'83000000-0000-0000-0000-000000000005','P1API revenue invoice allocation',0,120,0,120,'SGD',120),
  ('8c000000-0000-0000-0000-000000000031','8a000000-0000-0000-0000-000000000003',10,'83000000-0000-0000-0000-000000000003','P1API AR reverse allocation',80,0,80,0,'SGD',80),
  ('8c000000-0000-0000-0000-000000000032','8a000000-0000-0000-0000-000000000003',20,'83000000-0000-0000-0000-000000000005','P1API revenue reverse allocation',0,80,0,80,'SGD',80),
  ('8c000000-0000-0000-0000-000000000041','8a000000-0000-0000-0000-000000000004',10,'83000000-0000-0000-0000-000000000003','P1API AR cancel',100,0,100,0,'SGD',100),
  ('8c000000-0000-0000-0000-000000000042','8a000000-0000-0000-0000-000000000004',20,'83000000-0000-0000-0000-000000000005','P1API revenue cancel',0,100,0,100,'SGD',100),
  ('8c000000-0000-0000-0000-000000000051','8a000000-0000-0000-0000-000000000005',10,'83000000-0000-0000-0000-000000000003','P1API AR bounce',70,0,70,0,'SGD',70),
  ('8c000000-0000-0000-0000-000000000052','8a000000-0000-0000-0000-000000000005',20,'83000000-0000-0000-0000-000000000005','P1API revenue bounce',0,70,0,70,'SGD',70),
  -- Receipt JEs: Dr Bank/Cheques on Hand, Cr AR.
  ('8d000000-0000-0000-0000-000000000021','8b000000-0000-0000-0000-000000000002',10,'83000000-0000-0000-0000-000000000001','P1API bank manual allocation',120,0,120,0,'SGD',120),
  ('8d000000-0000-0000-0000-000000000022','8b000000-0000-0000-0000-000000000002',20,'83000000-0000-0000-0000-000000000003','P1API AR receipt manual allocation',0,120,0,120,'SGD',120),
  ('8d000000-0000-0000-0000-000000000031','8b000000-0000-0000-0000-000000000003',10,'83000000-0000-0000-0000-000000000001','P1API bank reverse allocation',80,0,80,0,'SGD',80),
  ('8d000000-0000-0000-0000-000000000032','8b000000-0000-0000-0000-000000000003',20,'83000000-0000-0000-0000-000000000003','P1API AR receipt reverse allocation',0,80,0,80,'SGD',80),
  ('8d000000-0000-0000-0000-000000000041','8b000000-0000-0000-0000-000000000004',10,'83000000-0000-0000-0000-000000000002','P1API cheques on hand bounce',70,0,70,0,'SGD',70),
  ('8d000000-0000-0000-0000-000000000042','8b000000-0000-0000-0000-000000000004',20,'83000000-0000-0000-0000-000000000003','P1API AR receipt bounce',0,70,0,70,'SGD',70),
  ('8d000000-0000-0000-0000-000000000051','8b000000-0000-0000-0000-000000000005',10,'83000000-0000-0000-0000-000000000001','P1API bank non cheque',30,0,30,0,'SGD',30),
  ('8d000000-0000-0000-0000-000000000052','8b000000-0000-0000-0000-000000000005',20,'83000000-0000-0000-0000-000000000003','P1API AR receipt non cheque',0,30,0,30,'SGD',30);

COMMIT;

-- ============================================================================
-- FINAL OUTPUT: COPY THESE VALUES INTO POSTMAN/CURL VARIABLES
-- ============================================================================

SELECT *
FROM (
  VALUES
    ('COMPANY_ID', '81000000-0000-0000-0000-000000000001'),
    ('CROSS_COMPANY_ID', '81000000-0000-0000-0000-000000000002'),
    ('ASSIGNED_CUSTOMER_ID', '85000000-0000-0000-0000-000000000001'),
    ('UNASSIGNED_CUSTOMER_ID', '85000000-0000-0000-0000-000000000002'),
    ('DRAFT_INVOICE_ID', '86000000-0000-0000-0000-000000000001'),
    ('DRAFT_RECEIPT_ID', '88000000-0000-0000-0000-000000000001'),
    ('OPEN_INVOICE_ID', '86000000-0000-0000-0000-000000000002'),
    ('POSTED_RECEIPT_ID', '88000000-0000-0000-0000-000000000002'),
    ('ACTIVE_ALLOCATION_ID', '89000000-0000-0000-0000-000000000001'),
    ('OPEN_UNALLOCATED_INVOICE_ID', '86000000-0000-0000-0000-000000000004'),
    ('CHEQUE_RECEIPT_ID', '88000000-0000-0000-0000-000000000004'),
    ('NON_CHQ_RECEIPT_ID', '88000000-0000-0000-0000-000000000005'),
    ('UNASSIGNED_DRAFT_INVOICE_ID', '86000000-0000-0000-0000-000000000006'),
    ('UNASSIGNED_DRAFT_RECEIPT_ID', '88000000-0000-0000-0000-000000000006')
) AS fixture(key, value);

-- Quick balance check for seeded JEs.
SELECT
  je.company_id,
  COUNT(*) AS je_count,
  COALESCE(SUM(je.total_debit), 0) AS total_debit,
  COALESCE(SUM(je.total_credit), 0) AS total_credit
FROM journal_entries je
WHERE je.company_id = '81000000-0000-0000-0000-000000000001'
  AND je.je_no LIKE 'P1API-%'
GROUP BY je.company_id;
